name: CI
on: 
  pull_request: 
    branches: [ master ] 
jobs: 
  echo_hello: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Run a one-line script 
        run: echo Hello Pull-Request
